Databases:
  AnimeChars:
    - ${ANIME_DATA_ROOT}/audio/{uri}.wav
Protocols:
  AnimeChars:
    SpeakerDiarization:
      Default:
        scope: file
        train:
          uri: ${ANIME_DATA_ROOT}/audio/train.lst
          annotation: ${ANIME_DATA_ROOT}/rttm/train.rttm
          annotated: ${ANIME_DATA_ROOT}/rttm/train.uem
        development:
          uri: ${ANIME_DATA_ROOT}/audio/development.lst
          annotation: ${ANIME_DATA_ROOT}/rttm/development.rttm
          annotated: ${ANIME_DATA_ROOT}/rttm/development.uem
